import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import { resolveMailRoot, resolveMaildirPath } from './paths.js';

import { resolveConfigPath } from '#config/load-accounts';
import { buildServiceName } from '#secrets/keychain';

import type { Account, AccountsConfig } from '#config/accounts.schema';

/* --------
 * Helpers
 * -------- */

function resolveMbsyncrcPath(): string {
  return join(dirname(resolveConfigPath()), 'mbsyncrc');
}

/**
 * Configuration block for one account.
 *
 * The password does not appear: `PassCmd` has mbsync itself read it from the Keychain at sync time.
 * It is the same principle that holds for the server — see `.claude/rules/security.md` §1.
 */
function buildAccountBlock(account: Account): string {
  const service = buildServiceName(account.id, 'imap');
  const maildir = resolveMaildirPath(account);

  return [
    `IMAPAccount ${account.id}`,
    `Host ${account.imap.host}`,
    `Port ${account.imap.port}`,
    `User ${account.imap.user}`,
    `PassCmd "/usr/bin/security find-generic-password -s '${service}' -a '${account.imap.user}' -w"`,
    'TLSType IMAPS',
    'CertificateFile /etc/ssl/cert.pem',
    '',
    `IMAPStore ${account.id}-remote`,
    `Account ${account.id}`,
    '',
    `MaildirStore ${account.id}-local`,
    `Path ${maildir}/`,
    `Inbox ${maildir}/INBOX`,
    'SubFolders Verbatim',
    '',
    `Channel ${account.id}`,
    `Far :${account.id}-remote:`,
    `Near :${account.id}-local:`,
    'Patterns *',
    // The mirror is a read-only cache: no local change ever travels back to the server.
    'Sync Pull',
    'Create Near',
    'Expunge None',
    'SyncState *',
    '',
  ].join('\n');
}

/* --------
 * Implementation
 * -------- */

/**
 * Generates `mbsyncrc` from the account configuration and returns its path.
 *
 * The file is derived: it is regenerated on every sync, so it cannot drift from `accounts.json`.
 */
export async function writeMbsyncrc(config: AccountsConfig): Promise<string> {
  const path = resolveMbsyncrcPath();
  const mirrored = config.accounts.filter((account) => account.mirror.enabled);

  const content = [
    '# Generated by mailbridge. Do not edit by hand: it is rewritten on every `mailbridge sync`.',
    `# Mirror root: ${resolveMailRoot()}`,
    '',
    ...mirrored.map((account) => buildAccountBlock(account)),
  ].join('\n');

  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, { encoding: 'utf8', mode: 0o600 });

  return path;
}

/**
 * The channels to sync, in the order they appear in the configuration.
 */
export function listMirroredChannels(config: AccountsConfig): string[] {
  return config.accounts.filter((account) => account.mirror.enabled).map((account) => account.id);
}
