import { execFile } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { promisify } from 'node:util';

import { withSyncLock } from './lock.js';
import { listMirroredChannels, writeMbsyncrc } from './mbsyncrc.js';
import { resolveMailRoot, resolveMaildirPath } from './paths.js';
import { assertMirrorTools } from './prerequisites.js';
import { recordSync } from './state.js';

import { resolveConfigPath } from '#config/load-accounts';
import { MailbridgeError } from '#shared/errors';
import { logger } from '#shared/logger';

import type { AccountsConfig } from '#config/accounts.schema';

/* --------
 * Constants
 * -------- */

const SYNC_TIMEOUT_MS = 15 * 60_000;

const INDEX_TIMEOUT_MS = 10 * 60_000;

const MAX_OUTPUT_BYTES = 8 * 1024 * 1024;

const execFileAsync = promisify(execFile);

/* --------
 * Types
 * -------- */

export interface SyncRunResult {
  accountId: string;
  ok: boolean
  /** Last lines of output, useful when something goes wrong. */
  detail: string | undefined;
}

export interface SyncSummary {
  runs: SyncRunResult[];
  indexedMessages: number | undefined;
  mailRoot: string;
}

export interface RunSyncOptions {
  /** Who started the sync, recorded in the lock: `cli`, `mcp`, `schedule`. */
  source?: string | undefined;
  /**
   * Accounts to sync. Absent = every account with the mirror enabled.
   *
   * An id that does not exist, or that has the mirror disabled, is an explicit error: a sync that
   * silently ignores what it was asked to do makes you believe it worked.
   */
  accountIds?: readonly string[] | undefined;
  /** Reports progress, for the CLI. It never receives credentials. */
  onProgress?: ((event: SyncProgressEvent) => void) | undefined;
}

export type SyncProgressEvent =
  | { kind: 'account-start'; accountId: string; position: number; total: number }
  | { kind: 'account-done'; accountId: string; ok: boolean }
  | { kind: 'index-start' }
  | { kind: 'index-done'; indexedMessages: number | undefined };

/* --------
 * Helpers
 * -------- */

function resolveNotmuchConfigPath(): string {
  return join(dirname(resolveConfigPath()), 'notmuch-config');
}

function tail(output: string, lines: number): string | undefined {
  const trimmed = output.trim();

  if (trimmed.length === 0) {
    return undefined;
  }

  return trimmed.split('\n').slice(-lines).join('\n');
}

/**
 * A dedicated notmuch configuration, so the mirror index does not interfere with any personal
 * notmuch installation the user may have.
 */
async function writeNotmuchConfig(): Promise<string> {
  const path = resolveNotmuchConfigPath();
  const mailRoot = resolveMailRoot();

  const content = [
    '# Generated by mailbridge. Do not edit by hand.',
    '[database]',
    `path=${mailRoot}`,
    '',
    '[new]',
    'tags=unread;inbox',
    'ignore=.mbsyncstate;.uidvalidity;.DS_Store',
    '',
    '[search]',
    'exclude_tags=',
    '',
  ].join('\n');

  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, { encoding: 'utf8', mode: 0o600 });

  return path;
}

/* --------
 * Implementation
 * -------- */

/**
 * Syncs the mirrors and reindexes. The sync is `Pull`: nothing local travels back to the server, so
 * the worst case is re-downloading — never losing.
 */
export async function runSync(config: AccountsConfig, options: RunSyncOptions = {}): Promise<SyncSummary> {
  // The lock wraps everything else: two mbsync runs on the same channel corrupt the sync state, and
  // with the scheduled sync active, overlapping with a manual one is only a matter of time.
  return withSyncLock(options.source ?? 'cli', async () => runSyncLocked(config, options));
}

async function runSyncLocked(config: AccountsConfig, options: RunSyncOptions): Promise<SyncSummary> {
  // ---- Options deconstruct
  const { accountIds, onProgress } = options;

  // Checked before anything else: without it a missing binary surfaces as `spawn mbsync ENOENT` repeated
  // per account, followed by a final error blaming notmuch — pointing at the wrong problem.
  await assertMirrorTools();

  // ---- Prepare
  const mbsyncrcPath = await writeMbsyncrc(config);
  const mirrored = listMirroredChannels(config);

  if (mirrored.length === 0) {
    throw new MailbridgeError('mirror_unavailable', 'No account has the mirror enabled.', {
      remediation: 'Enable the mirror on at least one account with `mailbridge account edit`.',
    });
  }

  // ---- Scope
  let channels: string[];

  if (accountIds === undefined) {
    channels = mirrored;
  } else {
    const unknown = accountIds.filter((accountId) => !mirrored.includes(accountId));

    if (unknown.length > 0) {
      throw new MailbridgeError('mirror_unavailable', `Cannot sync: ${unknown.join(', ')}.`, {
        remediation: `Accounts with the mirror enabled: ${mirrored.join(', ')}.`,
      });
    }

    channels = mirrored.filter((accountId) => accountIds.includes(accountId));
  }

  const selected = config.accounts.filter((account) => channels.includes(account.id));

  for (const account of selected) {
    await mkdir(resolveMaildirPath(account), { recursive: true });
  }

  // ---- Sync, one channel at a time so a broken account does not stop the others
  const runs: SyncRunResult[] = [];

  for (const [position, channel] of channels.entries()) {
    onProgress?.({ kind: 'account-start', accountId: channel, position: position + 1, total: channels.length });

    try {
      const { stdout, stderr } = await execFileAsync('mbsync', ['-c', mbsyncrcPath, channel], {
        timeout:   SYNC_TIMEOUT_MS,
        maxBuffer: MAX_OUTPUT_BYTES,
      });

      runs.push({ accountId: channel, ok: true, detail: tail(`${stdout}\n${stderr}`, 5) });
      onProgress?.({ kind: 'account-done', accountId: channel, ok: true });

      await recordSync(channel, {
        lastSyncAt:      new Date().toISOString(),
        lastSyncOk:      true,
        indexedMessages: undefined,
      });
    } catch (cause) {
      const detail = cause instanceof Error ? tail(cause.message, 5) : String(cause);

      logger.warn('account sync failed', { accountId: channel, detail });

      runs.push({ accountId: channel, ok: false, detail });
      onProgress?.({ kind: 'account-done', accountId: channel, ok: false });

      await recordSync(channel, {
        lastSyncAt:      new Date().toISOString(),
        lastSyncOk:      false,
        indexedMessages: undefined,
      });
    }
  }

  // ---- Index
  onProgress?.({ kind: 'index-start' });

  const notmuchConfigPath = await writeNotmuchConfig();
  let indexedMessages: number | undefined;

  try {
    await execFileAsync('notmuch', ['new'], {
      timeout:   INDEX_TIMEOUT_MS,
      maxBuffer: MAX_OUTPUT_BYTES,
      env:       { ...process.env, NOTMUCH_CONFIG: notmuchConfigPath },
    });

    const { stdout } = await execFileAsync('notmuch', ['count', '--output=messages', '*'], {
      timeout:   INDEX_TIMEOUT_MS,
      maxBuffer: 4096,
      env:       { ...process.env, NOTMUCH_CONFIG: notmuchConfigPath },
    });

    const parsed = Number.parseInt(stdout.trim(), 10);

    indexedMessages = Number.isNaN(parsed) ? undefined : parsed;
  } catch (cause) {
    throw new MailbridgeError('mirror_unavailable', 'notmuch indexing failed.', {
      remediation: 'Check that notmuch is installed: `brew install notmuch`.',
      cause,
    });
  }

  onProgress?.({ kind: 'index-done', indexedMessages });

  logger.info('sync completed', { channels: channels.length, indexedMessages });

  return { runs, indexedMessages, mailRoot: resolveMailRoot() };
}

/**
 * Path of the generated notmuch configuration. The search modules use it to talk to the right index.
 */
export function getNotmuchConfigPath(): string {
  return resolveNotmuchConfigPath();
}
