import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

import { getNotmuchConfigPath } from '#mirror/sync';
import { MailbridgeError } from '#shared/errors';

/* --------
 * Constants
 * -------- */

const NOTMUCH_TIMEOUT_MS = 20_000;

/** A very large result must not be able to exhaust the process memory. */
const MAX_OUTPUT_BYTES = 32 * 1024 * 1024;

const execFileAsync = promisify(execFile);

/* --------
 * Helpers
 * -------- */

/**
 * notmuch talks to the index generated by `mailbridge sync`, not to a personal installation: the
 * configuration always comes from `NOTMUCH_CONFIG`.
 */
function buildNotmuchEnv(): NodeJS.ProcessEnv {
  return { ...process.env, NOTMUCH_CONFIG: getNotmuchConfigPath() };
}

/* --------
 * Implementation
 * -------- */

export async function runNotmuch(args: readonly string[]): Promise<string> {
  try {
    const { stdout } = await execFileAsync('notmuch', [...args], {
      timeout:   NOTMUCH_TIMEOUT_MS,
      maxBuffer: MAX_OUTPUT_BYTES,
      env:       buildNotmuchEnv(),
    });

    return stdout;
  } catch (cause) {
    throw new MailbridgeError('search_failed', 'Running notmuch failed.', {
      remediation: 'Check that notmuch is installed and that the mirror has been indexed with `mailbridge sync`.',
      cause,
    });
  }
}

/**
 * Is `notmuch` available with a database? Determines whether search can use it.
 */
export async function isNotmuchAvailable(): Promise<boolean> {
  try {
    await execFileAsync('notmuch', ['count', '--output=messages', '*'], {
      timeout:   NOTMUCH_TIMEOUT_MS,
      maxBuffer: 4096,
      env:       buildNotmuchEnv(),
    });

    return true;
  } catch {
    return false;
  }
}
