import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

import { buildNotmuchQuery } from './notmuch-query.js';

import { locateInMirror } from '#mirror/paths';
import { getNotmuchConfigPath } from '#mirror/sync';
import { parseAddressHeader } from '#shared/address';
import { MailbridgeError } from '#shared/errors';
import { logger } from '#shared/logger';

import type { SearchCriteria } from './criteria.types.js';
import type { NotmuchQueryOptions } from './notmuch-query.js';
import type { SearchHit } from './search.types.js';

/* --------
 * Constants
 * -------- */

const NOTMUCH_TIMEOUT_MS = 20_000;

/** A very large result must not be able to exhaust the process memory. */
const MAX_OUTPUT_BYTES = 32 * 1024 * 1024;

const execFileAsync = promisify(execFile);

/* --------
 * Types
 * -------- */

interface NotmuchHeaders {
  Subject?: string;
  From?: string;
  To?: string;
  Cc?: string;
  Date?: string;
}

interface NotmuchMessage {
  id?: string;
  filename?: string | string[];
  timestamp?: number;
  tags?: string[];
  headers?: NotmuchHeaders;
}

/* --------
 * Helpers — process
 * -------- */

/**
 * notmuch talks to the index generated by `mailbridge sync`, not to a personal installation: the
 * configuration always comes from `NOTMUCH_CONFIG`.
 */
function buildNotmuchEnv(): NodeJS.ProcessEnv {
  return { ...process.env, NOTMUCH_CONFIG: getNotmuchConfigPath() };
}

async function runNotmuch(args: readonly string[]): Promise<string> {
  try {
    const { stdout } = await execFileAsync('notmuch', [...args], {
      timeout:   NOTMUCH_TIMEOUT_MS,
      maxBuffer: MAX_OUTPUT_BYTES,
      env:       buildNotmuchEnv(),
    });

    return stdout;
  } catch (cause) {
    throw new MailbridgeError('search_failed', 'Running notmuch failed.', {
      remediation: 'Check that notmuch is installed and that the mirror has been indexed with `mailbridge sync`.',
      cause,
    });
  }
}

/**
 * Is `notmuch` available with a database? Determines whether search can use it.
 */
export async function isNotmuchAvailable(): Promise<boolean> {
  try {
    await execFileAsync('notmuch', ['count', '--output=messages', '*'], {
      timeout:   NOTMUCH_TIMEOUT_MS,
      maxBuffer: 4096,
      env:       buildNotmuchEnv(),
    });

    return true;
  } catch {
    return false;
  }
}

/* --------
 * Helpers — parsing
 * -------- */

/**
 * `notmuch show` output is nested: a list of threads, each a list of messages with their own
 * replies. This flattens it in visit order.
 */
function flattenShowOutput(node: unknown, collected: NotmuchMessage[]): void {
  if (Array.isArray(node)) {
    for (const child of node) {
      flattenShowOutput(child, collected);
    }

    return;
  }

  if (node === null || typeof node !== 'object') {
    return;
  }

  const candidate = node as NotmuchMessage & { id?: unknown };

  if (typeof candidate.id === 'string') {
    collected.push(candidate);
  }
}

function firstFilename(filename: string | string[] | undefined): string | undefined {
  if (typeof filename === 'string') {
    return filename;
  }

  return Array.isArray(filename) ? filename[0] : undefined;
}

/* --------
 * Implementation
 * -------- */

/**
 * Searches the local mirror through notmuch.
 *
 * `hasAttachment` is applied here rather than in the query, because notmuch does not index it without
 * dedicated configuration: the filter relies on the `attachment` tag when present.
 */
export async function searchWithNotmuch(
  criteria: SearchCriteria,
  options: NotmuchQueryOptions = {},
): Promise<{ hits: SearchHit[]; query: string }> {
  // ---- Query build
  const query = buildNotmuchQuery(criteria, options);

  const raw = await runNotmuch([
    'show',
    '--format=json',
    '--body=false',
    '--entire-thread=false',
    query,
  ]);

  // ---- Parse
  let parsed: unknown;

  try {
    parsed = JSON.parse(raw);
  } catch (cause) {
    throw new MailbridgeError('search_failed', 'notmuch output could not be parsed.', { cause });
  }

  const messages: NotmuchMessage[] = [];

  flattenShowOutput(parsed, messages);

  // ---- Result mapping
  const hits: SearchHit[] = [];

  for (const message of messages) {
    const filename = firstFilename(message.filename);
    const location = filename === undefined ? undefined : locateInMirror(filename);
    const tags = message.tags ?? [];
    const hasAttachment = tags.includes('attachment');

    if (criteria.hasAttachment === true && !hasAttachment) {
      continue;
    }

    hits.push({
      accountId:  location?.accountId ?? criteria.accountId ?? 'unknown',
      folder:     location?.folder,
      messageId:  message.id,
      subject:    message.headers?.Subject ?? '(no subject)',
      from:       parseAddressHeader(message.headers?.From),
      to:         parseAddressHeader(message.headers?.To),
      date:       message.timestamp === undefined ? undefined : new Date(message.timestamp * 1000).toISOString(),
      isUnread:   tags.includes('unread'),
      isFlagged:  tags.includes('flagged'),
      hasAttachment,
      uid:        undefined,
    });
  }

  // ---- Sort and cap
  hits.sort((left, right) => (right.date ?? '').localeCompare(left.date ?? ''));

  logger.debug('notmuch search completed', { query, found: hits.length });

  return { hits: hits.slice(0, criteria.limit), query };
}
