import { execFile } from 'node:child_process';
import { chmod, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';

import { MailbridgeError } from '#shared/errors';
import { logger } from '#shared/logger';

/* --------
 * Constants
 * -------- */

/** Name shown in System Settings → Login Items → Allow in the Background. */
export const BUNDLE_DISPLAY_NAME = 'Mailbridge Sync';

export const BUNDLE_IDENTIFIER = 'com.marcocavanna.mailbridge';

const BUNDLE_DIRECTORY_NAME = 'MailbridgeSync.app';

const BUNDLE_EXECUTABLE_NAME = 'mailbridge-sync';

const CODESIGN_BIN = '/usr/bin/codesign';

const execFileAsync = promisify(execFile);

/* --------
 * Types
 * -------- */

export interface BundleConfig {
  /** Absolute path of the Node binary to use. */
  nodePath: string;
  /** Absolute path of `dist/cli/main.js`. */
  entryPath: string;
  version: string;
}

/* --------
 * Helpers
 * -------- */

export function resolveBundlePath(): string {
  return join(homedir(), 'Library', 'Application Support', 'mailbridge', BUNDLE_DIRECTORY_NAME);
}

export function resolveBundleExecutablePath(): string {
  return join(resolveBundlePath(), 'Contents', 'MacOS', BUNDLE_EXECUTABLE_NAME);
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * The bundle's `Info.plist`.
 *
 * `LSBackgroundOnly` and `LSUIElement` declare that it has no interface: without them macOS would
 * treat it as a regular app, with a Dock icon on every run.
 */
function buildInfoPlist(version: string): string {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    '<dict>',
    '  <key>CFBundleName</key>',
    `  <string>${escapeXml(BUNDLE_DISPLAY_NAME)}</string>`,
    '  <key>CFBundleDisplayName</key>',
    `  <string>${escapeXml(BUNDLE_DISPLAY_NAME)}</string>`,
    '  <key>CFBundleIdentifier</key>',
    `  <string>${escapeXml(BUNDLE_IDENTIFIER)}</string>`,
    '  <key>CFBundleExecutable</key>',
    `  <string>${escapeXml(BUNDLE_EXECUTABLE_NAME)}</string>`,
    '  <key>CFBundlePackageType</key>',
    '  <string>APPL</string>',
    '  <key>CFBundleShortVersionString</key>',
    `  <string>${escapeXml(version)}</string>`,
    '  <key>CFBundleVersion</key>',
    `  <string>${escapeXml(version)}</string>`,
    '  <key>LSBackgroundOnly</key>',
    '  <true/>',
    '  <key>LSUIElement</key>',
    '  <true/>',
    '</dict>',
    '</plist>',
    '',
  ].join('\n');
}

/**
 * The bundle's executable: forwards to Node the arguments received from launchd.
 *
 * The paths are baked in at generation time, quoted: a space in a path would break the command, and
 * `exec` avoids leaving a shell hanging around waiting for its child.
 *
 * The `MAILBRIDGE_NODE=` marker lets `schedule status` read back which Node is in use without having
 * to interpret the script.
 */
function buildExecutableScript(config: BundleConfig): string {
  return [
    '#!/bin/sh',
    '# Generated by mailbridge. Do not edit: it is rewritten on every `mailbridge schedule enable`.',
    `# MAILBRIDGE_NODE=${config.nodePath}`,
    `# MAILBRIDGE_ENTRY=${config.entryPath}`,
    '',
    `exec "${config.nodePath}" "${config.entryPath}" "$@"`,
    '',
  ].join('\n');
}

/* --------
 * Implementation
 * -------- */

/**
 * Creates the bundle launchd runs in place of Node, and returns the path of its executable.
 *
 * The reason is entirely about legibility for the user: in System Settings a background item is
 * attributed to **whoever signs the launched executable**, not to the LaunchAgent's `Label`. Pointing
 * straight at a Node binary, macOS announces "an item from Node.js Foundation", which tells the reader
 * nothing and cannot be disabled with any understanding of what it is.
 *
 * The signature is ad-hoc (`codesign -s -`): no Developer ID is required, what is required is that the
 * bundle has an identity of its own.
 */
export async function writeAppBundle(config: BundleConfig): Promise<string> {
  const bundlePath = resolveBundlePath();
  const executablePath = resolveBundleExecutablePath();

  // ---- Contents
  await mkdir(join(bundlePath, 'Contents', 'MacOS'), { recursive: true });
  await writeFile(join(bundlePath, 'Contents', 'Info.plist'), buildInfoPlist(config.version), 'utf8');
  await writeFile(executablePath, buildExecutableScript(config), 'utf8');
  await chmod(executablePath, 0o755);

  // ---- Signature
  try {
    await execFileAsync(CODESIGN_BIN, [
      '--force',
      '--sign', '-',
      '--identifier', BUNDLE_IDENTIFIER,
      bundlePath,
    ], { timeout: 30_000 });
  } catch (cause) {
    throw new MailbridgeError('config_invalid', 'Cannot sign the scheduled-sync bundle.', {
      remediation: 'Check that the Xcode command line tools are installed: `xcode-select --install`.',
      cause,
    });
  }

  logger.info('scheduled-sync bundle generated', { bundlePath });

  return executablePath;
}

/**
 * Reads which Node the installed bundle is using. `undefined` when the bundle is absent or unreadable.
 */
export async function readBundleNodePath(): Promise<string | undefined> {
  try {
    const script = await readFile(resolveBundleExecutablePath(), 'utf8');
    const match = /^# MAILBRIDGE_NODE=(.+)$/m.exec(script);

    return match?.[1];
  } catch {
    return undefined;
  }
}

export async function removeAppBundle(): Promise<void> {
  await rm(resolveBundlePath(), { recursive: true, force: true });

  logger.info('scheduled-sync bundle removed');
}
